# image will be published to ghcr.io/<user>/<name>
name: kinoite-custom-intel-v2

# description will be included in the image's metadata
description: "Customized Fedora Kinoite image, based on BlueBuild. Intended for my Intel Dell Optiplex"

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main

# latest is also supported if you want new updates ASAP
image-version: 43

# module configuration, executed in order
# you can include multiple instances of the same module

modules:
  - type: files

    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo

    install:
      skip-unavailable: false
      packages:
        - repo: tailscale-stable
          packages:
            - tailscale

        # CLI Utilities #####################
        - binutils
        - btop
        - fastfetch
        - fish
        - igt-gpu-tools
        - lm_sensors
        - podman-compose
        - tealdeer

        # GUI Apps ##########################
        - gnome-disk-utility
        - goverlay
        - gwenview
        - kvantum
        - okular

        # Configuration and libraries #######
        - hunspell-es
        - hunspell-es-CL
        - steam-devices

        # Fonts #############################
        - rsms-inter-fonts
        - rsms-inter-vf-fonts

    remove:
      packages:
        # GUI Apps ##########################
        - firefox
        - kate

        # CLI Utilities #####################
        - nvtop
        - vim-common
        - vim-data
        - vim-enhanced
        - vim-filesystem
        - vim-minimal
        - xrandr

        # Configs, libs, addons and filesystem layouts
        - firefox-langpacks
        - mozilla-filesystem
        - braille-printer-app
        - fcitx5-chinese-addons
        - fcitx5-chinese-addons-data
        - fcitx5-hangul
        - fcitx5-libthai
        - fcitx5-mozc
        - fcitx5-sayura
        - fcitx5-unikey
        - ibus-anthy
        - ibus-anthy-python
        - ibus-chewing
        - ibus-hangul
        - ibus-libpinyin
        - kasumi-common
        - kasumi-unicode
        - virtualbox-guest-additions

        ######################
        # Intel related
        - libva-intel-media-driver  #Vaapi for newer intel gpus (unsupported on mine)
        - intel-vsc-firmware        #Webcams and vision firmware
        - iwlegacy-firmware         #Wifi firmware for legacy intel wifi cards

        # Other firmware ####################
        - atheros-firmware          #Atheros wifi/bluetooth
        - brcmfmac-firmware         #Broadcom/Cypress wifi/bluetooth
        - b43-fwcutter              #Firmware extraction tool for broadcom
        - b43-openfwwf              #Open firmware for certain broadcom wlan chips.
        - cirrus-audio-firmware     #Cirrus amplifiers and codecs
        - libertas-firmware         #Marvel libertas USB wifi adapters
        - nvidia-gpu-firmware       #Nvidia GPUs
        - nxpwireless-firmware      #NXP Wifi/Bluetooth
        - tiwilink-firmware         #Texas instruments wifi/bluetooth

        # Fonts #############################
        - madan-fonts #Nepali fonts
        - paktype-naskh-basic-fonts #Arabic, Farsi, Urdu and Sindhi fonts
        - rit-meera-new-fonts #Malayalam script
        - rit-rachana-fonts #Malayalam script
        - sil-padauk-fonts #Burmese and Myanmar script
        - vazirmatn-vf-fonts #Persian/arabic font

        - default-fonts-am
        - default-fonts-ar
        - default-fonts-as
        - default-fonts-ast
        - default-fonts-be
        - default-fonts-bg
        - default-fonts-bn
        - default-fonts-bo
        - default-fonts-br
        - default-fonts-chr
        - default-fonts-cjk-mono
        - default-fonts-cjk-serif
        - default-fonts-dv
        - default-fonts-dz
        - default-fonts-el
        - default-fonts-eo
        - default-fonts-eu
        - default-fonts-fa
        - default-fonts-gu
        - default-fonts-he
        - default-fonts-hi
        - default-fonts-hy
        - default-fonts-ia
        - default-fonts-iu
        - default-fonts-ka
        - default-fonts-kab
        - default-fonts-km
        - default-fonts-kn
        - default-fonts-ku
        - default-fonts-lo
        - default-fonts-mai
        - default-fonts-ml
        - default-fonts-mni
        - default-fonts-mr
        - default-fonts-my
        - default-fonts-nb
        - default-fonts-ne
        - default-fonts-nn
        - default-fonts-nqo
        - default-fonts-nr
        - default-fonts-nso
        - default-fonts-or
        - default-fonts-other-mono
        - default-fonts-other-sans
        - default-fonts-other-serif
        - default-fonts-pa
        - default-fonts-ru
        - default-fonts-sat
        - default-fonts-si
        - default-fonts-ss
        - default-fonts-syr
        - default-fonts-ta
        - default-fonts-te
        - default-fonts-th
        - default-fonts-tn
        - default-fonts-ts
        - default-fonts-uk
        - default-fonts-ur
        - default-fonts-ve
        - default-fonts-vi
        - default-fonts-xh
        - default-fonts-yi
        - default-fonts-zu

        - google-noto-naskh-arabic-vf-fonts
        - google-noto-sans-arabic-vf-fonts
        - google-noto-sans-armenian-vf-fonts
        - google-noto-sans-balinese-fonts
        - google-noto-sans-bengali-vf-fonts
        - google-noto-sans-canadian-aboriginal-vf-fonts
        - google-noto-sans-cherokee-vf-fonts
        - google-noto-sans-cjk-fonts
        - google-noto-sans-devanagari-vf-fonts
        - google-noto-sans-ethiopic-vf-fonts
        - google-noto-sans-georgian-vf-fonts
        - google-noto-sans-gujarati-vf-fonts
        - google-noto-sans-gurmukhi-vf-fonts
        - google-noto-sans-hebrew-vf-fonts
        - google-noto-sans-javanese-fonts
        - google-noto-sans-kannada-vf-fonts
        - google-noto-sans-khmer-vf-fonts
        - google-noto-sans-lao-vf-fonts
        - google-noto-sans-meetei-mayek-vf-fonts
        - google-noto-sans-mono-cjk-vf-fonts
        - google-noto-sans-nko-fonts
        - google-noto-sans-ol-chiki-vf-fonts
        - google-noto-sans-oriya-vf-fonts
        - google-noto-sans-sinhala-vf-fonts
        - google-noto-sans-sundanese-fonts
        - google-noto-sans-syriac-vf-fonts
        - google-noto-sans-tamil-vf-fonts
        - google-noto-sans-telugu-vf-fonts
        - google-noto-sans-thaana-vf-fonts
        - google-noto-sans-thai-vf-fonts
        - google-noto-serif-armenian-vf-fonts
        - google-noto-serif-bengali-vf-fonts
        - google-noto-serif-cjk-vf-fonts
        - google-noto-serif-devanagari-vf-fonts
        - google-noto-serif-ethiopic-vf-fonts
        - google-noto-serif-georgian-vf-fonts
        - google-noto-serif-gujarati-vf-fonts
        - google-noto-serif-gurmukhi-vf-fonts
        - google-noto-serif-hebrew-vf-fonts
        - google-noto-serif-kannada-vf-fonts
        - google-noto-serif-khmer-vf-fonts
        - google-noto-serif-lao-vf-fonts
        - google-noto-serif-oriya-vf-fonts
        - google-noto-serif-sinhala-vf-fonts
        - google-noto-serif-tamil-vf-fonts
        - google-noto-serif-telugu-vf-fonts
        - google-noto-serif-thai-vf-fonts

        - jomolhari-fonts

  - type: default-flatpaks
    configurations:
      - notify: false

        scope: system
        install:
          - app.zen_browser.zen
          - com.github.tchx84.Flatseal
          - io.github.thetumultuousunicornofdarkness.cpu-x
          - org.kde.haruna
          - org.kde.kcalc
          - com.bitwarden.desktop
          - com.vscodium.codium
          - dev.zed.Zed

  - type: signing
      # this sets up the proper policy & signing files for signed images to work fully
